/** @type {import('tailwindcss').Config} */

export default {
  //always include these classes in the CSS output.
  // This ensures that dynamic classes like bg-pokemon-grass/15 are available at runtime,
  // allowing the backgrounds and type badges to display their correct colors instead of appearing white or unstyled.
  safelist: [
    'bg-pokemon-normal',
    'bg-pokemon-fire',
    'bg-pokemon-water',
    'bg-pokemon-electric',
    'bg-pokemon-grass',
    'bg-pokemon-ice',
    'bg-pokemon-fighting',
    'bg-pokemon-poison',
    'bg-pokemon-ground',
    'bg-pokemon-flying',
    'bg-pokemon-psychic',
    'bg-pokemon-bug',
    'bg-pokemon-rock',
    'bg-pokemon-ghost',
    'bg-pokemon-dragon',
    'bg-pokemon-dark',
    'bg-pokemon-steel',
    'bg-pokemon-fairy',
    'bg-pokemon-default',
    'bg-pokemon-normal/15',
    'bg-pokemon-fire/15',
    'bg-pokemon-water/15',
    'bg-pokemon-electric/15',
    'bg-pokemon-grass/15',
    'bg-pokemon-ice/15',
    'bg-pokemon-fighting/15',
    'bg-pokemon-poison/15',
    'bg-pokemon-ground/15',
    'bg-pokemon-flying/15',
    'bg-pokemon-psychic/15',
    'bg-pokemon-bug/15',
    'bg-pokemon-rock/15',
    'bg-pokemon-ghost/15',
    'bg-pokemon-dragon/15',
    'bg-pokemon-dark/15',
    'bg-pokemon-steel/15',
    'bg-pokemon-fairy/15',
    'bg-pokemon-default/15',
  ],
};
